---
- name: Start the EC2 instances
  ec2:
    aws_access_key: "{{ aws_access_key }}"
    aws_secret_key: "{{ aws_secret_key }}"
    instance_ids: '{{ instance_ids1 }}'
    region: '{{ aws_region }}'
    state: running
    wait: True
    vpc_subnet_id: "{{ vpc_subnet_id }}"
    assign_public_ip: yes
  register: ec2
- name: Save EC2 IP to inventory file
  copy:
    content: "[ec2one]{{'\n'}}{{ item.public_ip }}"
    dest: /etc/ansible/ec2_ips
  with_items: "{{ ec2.instances }}"

- name: Create Or Update Security Group
  ec2_group:
    name: "launch-wizard-1"
    description: "custom_rule_by_st"
    aws_access_key: "{{ aws_access_key }}"
    aws_secret_key: "{{ aws_secret_key }}"
    vpc_id: "{{ vpc_id }}"
    region: "{{ aws_region }}"
    rules:
      - proto: "tcp"
        from_port: "3389"
        to_port: "3389"
        cidr_ip: "{{ your_ip1 }}/32"
      - proto: "tcp"
        from_port: "3389"
        to_port: "3389"
        cidr_ip: "{{ your_ip2 }}/32"
      - proto: "tcp"
        from_port: "3389"
        to_port: "3389"
        cidr_ip: "{{ your_ip3 }}/32"
